
spring:
   application:
        name: gateway

   devtools:
      livereload:
         port: 35733
         
server:
    port: 8080
    servlet:
       context-path: /gateway

eureka:
   instance:
      prefer-ip-address: true
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8081/eureka/
       
zuul:
   sensitive-headers: Cookie